### PR TITLE
Little improvements and optimizations

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
@danbev please, review these changes

### CODE REVIEW

**Comment by danbev** [comment]
:+1:

**Comment by edewit** [comment]
:+1:

**Comment by matzew** [comment]
Thanks @idelpivnitskiy

**Comment by matzew** [comment]
Btw. @idelpivnitskiy worth to update to Netty-4.1.0.Beta5 ?

**Comment by idelpivnitskiy** [comment]
@matzew planned it in next PR :)

**Pull request merged**
