### PR TITLE
Remove usage of deprecated SslContext.newServerContext(...)

### PR DESCRIPTION
**Pull request by idelpivnitskiy**

### CODE REVIEW

**Comment by matzew** [comment]
@idelpivnitskiy that's an 'api' change in latest netty ?

**Comment by idelpivnitskiy** [comment]
@matzew yes

**Comment by matzew** [comment]
thanks, @idelpivnitskiy

**Comment by matzew** [comment]
@idelpivnitskiy btw. feel free to hangout w/ on IRC :-)

**Pull request merged**
