### PR TITLE
remove staging repo and use released lib

### PR DESCRIPTION
**Pull request by matzew**
getting ready for our first release, updating the lastest of Netty

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc @lholmquist wanna do a review/test ?

**Comment by lholmquist** [comment]
:eyes:

**Comment by lholmquist** [comment]
:+1:   `mvn clean install`'d good

**Comment by lholmquist** [comment]
AH,  i tested the sync server,  hold on a minute

**Comment by lholmquist** [comment]
ok, :+1:   good to go

**Comment by matzew** [comment]
landed

**Pull request merged**
