### PR TITLE
Update to Netty 4.1.0.Beta6-SNAPSHOT

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
**ATTENTION**: not for merging, only to analyze and try to resolve the next bug: https://github.com/aerogear/aerogear-webpush-server/pull/14#issuecomment-133211178.

**Problem**: WebPush Server does not work properly after update to Netty 4.1.0.Beta5 (see branch https://github.com/idelpivnitskiy/aerogear-webpush-server/tree/return_console or previous commut https://github.com/aerogear/aerogear-webpush-server/commit/1b41b9d35e22ab4b3d5a223a1b3d676724cb23c6) or to 4.1.0.Beta6-SNAPSHOT (current version).
> If you open two consoles (I mean WebPush Console), execute subscribe and monitor in the first one and notify through the second one, you will not receive a push message on the first console. But if you send monitor request again, you will receive all stacked push messages, but won't receive new ones.

Here is an example, how you can reproduce the problem:
1. Open the first terminal, go to the `server-netty` folder and start the WebPush Server: `mvn exec:exec`
2. Open the second terminal, go to the `console`  folder and start the WebPush Console: `mvn exec:exec`
3. Open the third terminal and execute previous step again.
4. Execute following command on the first Console:
```
[webpush]$ connecnt
[webpush]$ register
[webpush]$ subscribe --url url
(Use the WebLink of type urn:ietf:params:push:sub from the registration stage above as the url option)
[webpush]$ monitor --url url
(Use the WebLink of type urn:ietf:params:push:reg from the registration stage above as the url option)
```
Execute following command on the second Console:
```
[webpush]$ connect
[webpush]$ notify --url url --payload hello
(Use the location header value from the subscription response above as the url option)
```
WebPush Console documentation: https://github.com/aerogear/aerogear-webpush-server/blob/master/console/README.md 

Here is a log for the 4 and 5 steps:
_console 1:_
```
[webpush]$ connect 
Connected to [localhost:8443][channelId=15180db4]
[webpush]$ register 
> DefaultHttp2Headers[:authority: localhost:8443, :method: POST, :path: /webpush/register, :scheme: https]
< [streamid:3] DefaultHttp2Headers[:status: 201, access-control-allow-origin: *, access-control-expose-headers: Link, Cache-Control, Location, cache-control: private, max-age=604800000, link: <webpush/aggregate/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b>;rel="urn:ietf:params:push:aggregate", link: <webpush/reg/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b>;rel="urn:ietf:params:push:reg", link: <webpush/subscribe/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b>;rel="urn:ietf:params:push:sub", location: webpush/reg/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b]
[webpush]$ subscribe --url webpush/subscribe/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b
> DefaultHttp2Headers[:authority: localhost:8443, :method: POST, :path: webpush/subscribe/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b, :scheme: https]
< [streamid:5] DefaultHttp2Headers[:status: 201, access-control-allow-origin: *, access-control-expose-headers: Location, cache-control: private, max-age=604800000, location: /webpush/gnc8N8hlO5TxrF7IuTkUM798vijV9PnCQgTHjOqAbr9C2YjMB8sx1oYsvBp%2BJcOKiGyUBy1v8xBvbNLlSgDrjRKG8q3hqCnK0VenTACfZnPDfGHG1fd%2FsHKntMJdiO71AUhSey7fyDB9]
[webpush]$ monitor --url webpush/reg/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b
> DefaultHttp2Headers[:authority: localhost:8443, :method: GET, :path: webpush/reg/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b, :scheme: https]
< [streamid:7] DefaultHttp2Headers[:status: 200, access-control-allow-origin: *, access-control-expose-headers: Link, Cache-Control, cache-control: private, max-age=604800000, link: <webpush/aggregate/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b>;rel="urn:ietf:params:push:aggregate", link: <webpush/subscribe/b2ae8f16-2ac6-4a5a-8f07-d43c27a9db9b>;rel="urn:ietf:params:push:sub"]
```
Server log for _console 1_:
```
[nioEventLoopGroup-2-1] INFO io.netty.handler.logging.LoggingHandler - [id: 0xec6da852, /127.0.0.1:8443] RECEIVED: [id: 0x5bdb089f, /127.0.0.1:57149 => /127.0.0.1:8443]
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=3, method=POST, path=/webpush/register, endstream=false
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onDataRead. streamId=3, path=/webpush/register, endstream=true
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Registered DefautRegistration[id=9ddfee80-1de4-430a-b326-809ffa0ef938, uri=webpush/reg/9ddfee80-1de4-430a-b326-809ffa0ef938, subscribeUri=webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938, aggregateUri=webpush/aggregate/9ddfee80-1de4-430a-b326-809ffa0ef938]
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=5, method=POST, path=webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938, endstream=false
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onDataRead. streamId=5, path=webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938, endstream=true
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Subscription DefaultChannel[registrationId=9ddfee80-1de4-430a-b326-809ffa0ef938, id=3faed9be-c995-4182-8d76-d9f60bf12e74, endpoint=J0ZyLZR980VQDla5VqdOpoJnwL2j0K449PHG0YwYltxM644IF20JJJB7HG68CHLI9MnIhpxKyjru8Rn9SiZimK1tBAR6U4CsatktRkrRKOp9wKL5KgudgOxNd7%2B%2FZDS72U8nf%2FDrpXBa, message=Optional.empty]
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=7, method=GET, path=webpush/reg/9ddfee80-1de4-430a-b326-809ffa0ef938, endstream=true
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Monitor ctx=ChannelHandlerContext(WebPushHttp2Handler#0, [id: 0x5bdb089f, /127.0.0.1:57149 => /127.0.0.1:8443]), registrationId=9ddfee80-1de4-430a-b326-809ffa0ef938, pushPromiseStreamId=2, headers=DefaultHttp2Headers[:status: 200, access-control-allow-origin: *, access-control-expose-headers: Link, Cache-Control, link: <webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:sub", link: <webpush/aggregate/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:aggregate", cache-control: private, max-age=604800000]
```
_console 2:_
```
[webpush]$ connect 
Connected to [localhost:8443][channelId=9b736227]
[webpush]$ notify --url /webpush/gnc8N8hlO5TxrF7IuTkUM798vijV9PnCQgTHjOqAbr9C2YjMB8sx1oYsvBp%2BJcOKiGyUBy1v8xBvbNLlSgDrjRKG8q3hqCnK0VenTACfZnPDfGHG1fd%2FsHKntMJdiO71AUhSey7fyDB9 --payload asd
```
Server log for _console 2_:
```
[nioEventLoopGroup-2-1] INFO io.netty.handler.logging.LoggingHandler - [id: 0xec6da852, /127.0.0.1:8443] RECEIVED: [id: 0x86977a65, /127.0.0.1:57151 => /127.0.0.1:8443]
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=3, method=PUT, path=/webpush/J0ZyLZR980VQDla5VqdOpoJnwL2j0K449PHG0YwYltxM644IF20JJJB7HG68CHLI9MnIhpxKyjru8Rn9SiZimK1tBAR6U4CsatktRkrRKOp9wKL5KgudgOxNd7%2B%2FZDS72U8nf%2FDrpXBa, endstream=false
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onDataRead. streamId=3, path=/webpush/J0ZyLZR980VQDla5VqdOpoJnwL2j0K449PHG0YwYltxM644IF20JJJB7HG68CHLI9MnIhpxKyjru8Rn9SiZimK1tBAR6U4CsatktRkrRKOp9wKL5KgudgOxNd7%2B%2FZDS72U8nf%2FDrpXBa, endstream=true
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Handle notification Client[streamid=2, ctx=ChannelHandlerContext(WebPushHttp2Handler#0, [id: 0x5bdb089f, /127.0.0.1:57149 => /127.0.0.1:8443]), headersSent=false] payload asd
```
**At this moment the sent push message (asd) must be received by _console 1_. But this doesn't happen. And this is a problem!**

You could send any request to the server again on _console 1_ (for example, `monitor`) and you will receive the message:
```
[webpush]$ monitor --url webpush/reg/9ddfee80-1de4-430a-b326-809ffa0ef938
> DefaultHttp2Headers[:method: GET, :path: webpush/reg/9ddfee80-1de4-430a-b326-809ffa0ef938, :authority: localhost:8443, :scheme: https]
< [streamid:9] DefaultHttp2Headers[:status: 200, access-control-allow-origin: *, access-control-expose-headers: Link, Cache-Control, link: <webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:sub", link: <webpush/aggregate/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:aggregate", cache-control: private, max-age=604800000]
< [streamid:2] DefaultHttp2Headers[]
< [streamid:2] asd
```
Server log for _console 1_:
```
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=9, method=GET, path=webpush/reg/9ddfee80-1de4-430a-b326-809ffa0ef938, endstream=true
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Monitor ctx=ChannelHandlerContext(WebPushHttp2Handler#0, [id: 0x5bdb089f, /127.0.0.1:57149 => /127.0.0.1:8443]), registrationId=9ddfee80-1de4-430a-b326-809ffa0ef938, pushPromiseStreamId=4, headers=DefaultHttp2Headers[:status: 200, access-control-allow-origin: *, access-control-expose-headers: Link, Cache-Control, link: <webpush/subscribe/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:sub", link: <webpush/aggregate/9ddfee80-1de4-430a-b326-809ffa0ef938>;rel="urn:ietf:params:push:aggregate", cache-control: private, max-age=604800000]
```
But **you will not receive the new ones from _console 2_ again**:
```
[webpush]$ notify --url /webpush/2Sr8L7Vi0YBXndvPDzZvHmZyjzydd0FmQ3oHIvYm5g7FXbYbKNh1GRvxEVAxDj8jJUkBdFRQknTRk0TOY7QB4QGvLvDEt9PB%2Ff6xMulpux9eFp75B7aUUorLOmxD0xD2XFGpWntSxSMq --payload asdqwe123
> DefaultHttp2Headers[:authority: localhost:8443, :method: PUT, :path: /webpush/2Sr8L7Vi0YBXndvPDzZvHmZyjzydd0FmQ3oHIvYm5g7FXbYbKNh1GRvxEVAxDj8jJUkBdFRQknTRk0TOY7QB4QGvLvDEt9PB%2Ff6xMulpux9eFp75B7aUUorLOmxD0xD2XFGpWntSxSMq, :scheme: https
```
Server log for _console 2_:
```
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onHeadersRead. streamId=5, method=PUT, path=/webpush/J0ZyLZR980VQDla5VqdOpoJnwL2j0K449PHG0YwYltxM644IF20JJJB7HG68CHLI9MnIhpxKyjru8Rn9SiZimK1tBAR6U4CsatktRkrRKOp9wKL5KgudgOxNd7%2B%2FZDS72U8nf%2FDrpXBa, endstream=false
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - onDataRead. streamId=5, path=/webpush/J0ZyLZR980VQDla5VqdOpoJnwL2j0K449PHG0YwYltxM644IF20JJJB7HG68CHLI9MnIhpxKyjru8Rn9SiZimK1tBAR6U4CsatktRkrRKOp9wKL5KgudgOxNd7%2B%2FZDS72U8nf%2FDrpXBa, endstream=true
[nioEventLoopGroup-3-2] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Handle notification Client[streamid=4, ctx=ChannelHandlerContext(WebPushHttp2Handler#0, [id: 0x5bdb089f, /127.0.0.1:57149 => /127.0.0.1:8443]), headersSent=false] payload asdasd
```
The _console 1_ is silent again.

**Note**: when you use only one console (== one connection to WebPush Server) or Netty 4.1.0.Beta4, it works well.

My system:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T20:29:23+03:00)
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-62-generic", arch: "amd64", family: "unix". Ubuntu 14.04.3
```

### CODE REVIEW

**Comment by idelpivnitskiy** [comment]
Interesting, all push messages, which are registered on the server, but aren't sent to the client (according to bug) will be sent after any new client request, even after `GO_AWAY`:
```
[nioEventLoopGroup-3-1] TRACE org.jboss.aerogear.webpush.netty.WebPushHttp2Handler - 
----------------INBOUND--------------------
GO_AWAY: lastStreamId=2, errorCode=0, length=0, bytes=
------------------------------------
[nioEventLoopGroup-3-1] TRACE org.jboss.aerogear.webpush.netty.WebPushHttp2Handler - 
----------------OUTBOUND--------------------
HEADERS: streamId=2, headers=EmptyHttp2Headers[], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------
[nioEventLoopGroup-3-1] TRACE org.jboss.aerogear.webpush.netty.WebPushHttp2Handler - 
----------------OUTBOUND--------------------
DATA: streamId=2, padding=0, endStream=false, length=3, bytes=617364
------------------------------------
[nioEventLoopGroup-3-1] INFO org.jboss.aerogear.webpush.netty.WebPushFrameListener - Removed client regIdClient[streamid=2, ctx=ChannelHandlerContext(WebPushHttp2Handler#0, [id: 0x6eaa23e7, /127.0.0.1:32831 :> /127.0.0.1:8443]), headersSent=true]
```

**Comment by Scottmitch** [comment]
@idelpivnitskiy - From an HTTP/2 standpoint the message trace you provided seems OK. the GOAWAY indicates that new streams cannot be created, and the highest stream ID it is willing to accept frame on is `2`.  So the HEADERS and DATA frames after the GOAWAY seem to be in compliance with the spec.  Do you have a trigger point when a GOAWAY is received that may be jump starting your application to take action?

**Comment by idelpivnitskiy** [comment]
@Scottmitch thanks for paining attention!

The problem is not in a GOAWAY frame. The problem is that push messages are not sending to the client _immediattely_, if server saves the client's context. https://github.com/idelpivnitskiy/aerogear-webpush-server/blob/4.1.0.Beta6-SNAPSHOT/server-netty/src/main/java/org/jboss/aerogear/webpush/netty/WebPushFrameListener.java#L203-L213
I haven't got any outbound frames after these lines of code. But it worked well with Netty 4.1.0.Beta4

**Comment by idelpivnitskiy** [comment]
@Scottmitch I've debugged it and found out the reason of the problem. Will write a report to the Netty's issue.

**Comment by idelpivnitskiy** [comment]
@danbev @matzew @sebastienblanc 
This is not a bug of Netty. They only remove explicit flushes to the outbound channels for performance reasons. For more information, see Netty's issue above.
Fixed in the new draft #14

**Pull request closed without merging**
