### PR TITLE
Adding zip distributions for WebPush Console

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Currently the process of running the WebPush Console is pretty
complicated. This commit aim to simplify the work needed to get the
console running.

Modifications:
We now provide distributions of the console specific for
different java versions. These distributions will include the correct
NPN or ALPN TLS extension libs and also a shell script to start the
server. The distributions also contain a readme file the shows the
command to start the console for evironments that don't support shell
scripts.

Result:
To start a console for a specific version of Java it is only a matter
unzipping and running the shell script:

$ unzip -d java7_25 webpush-console-7_0_25.zip
$ cd java7_25
$ ./console.sh

### CODE REVIEW

**Comment by danbev** [comment]
@abstractj @lholmquist Would you guys mind doing a review?

To test build the complete project and after that you should see a number of zip files in ```console/target```. These zip files are named after the Java version that belong to (have to be run with). 
With the correct Java version execute the following commands:
```shell
$ unzip -d java7_25 webpush-console-7_0_25.zip
$ cd java7_25
$ ./console.sh
```
The above would be used against the node-webpush-server. 

Below are pre-built dists which will later be installed into the maven repository so we can later provide links for our users. 
[webpush-console-0.0.1-SNAPSHOT-7_0_25.zip](https://mwufbwkztk.localtunnel.me/dists/webpush-console-0.0.1-SNAPSHOT-7_0_25.zip)
[webpush-console-0.0.1-SNAPSHOT-7_0_67.zip](https://mwufbwkztk.localtunnel.me/dists/webpush-console-0.0.1-SNAPSHOT-7_0_67.zip)
[webpush-console-0.0.1-SNAPSHOT-7_0_72.zip](https://mwufbwkztk.localtunnel.me/dists/webpush-console-0.0.1-SNAPSHOT-7_0_72.zip)
[webpush-console-0.0.1-SNAPSHOT-8.zip](https://mwufbwkztk.localtunnel.me/dists/webpush-console-0.0.1-SNAPSHOT-8.zip)

**Comment by lholmquist** [comment]
I'm on it with my :eyes:

**Comment by lholmquist** [comment]
what is the reasoning behind having 3 java 7 zip's

**Comment by danbev** [comment]
@lholmquist The have different versions of NPN in them to work correctly.

**Comment by abstractj** [comment]
@danbev landed!

**Pull request merged**
