### PR TITLE
Change Netty version to 4.1.0.beta4-SNAPSHOT.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
We are currently using version 5.0.0.Alpha2-SNAPSHOT. But to release we
need a non-snapshot version. There will be a 4.1.0.beta4 release shortly
and we should update our code to make sure it work with that version.
This will make it easy for us to change to the non-snapshot version once
it is available.

Modifications:
Updated the version in the pom.xml and make modifications required for
the difference in Netty code base between 5.0.0 and 4.1.

Result:
Everything works as before and we'll be able to switch to 4.1.0.beta4
when it is available.

JIRA:
https://issues.jboss.org/browse/AGSYNC-46

### CODE REVIEW

**Comment by danbev** [comment]
@abstractj @matzew Would you guys mind to review?

To test build, with ```mvn clean install```, the complete project and after that you should see a number of zip files in ```console/target```. These zip files are named after the Java version that belong to (have to be run with). 

To test against the node-webpush-server. (make sure you are using the correct Java 7 version)
```shell
$ unzip -d java7_25 webpush-console-7_0_25.zip
$ cd java7_25
$ ./console.sh
```

To test against our WebPush Server use Java 1.8:
```shell
$ unzip -d java8 webpush-console-8.zip
$ cd java8
$ ./console.sh
```

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
Java: all fine

Node:  I was able to connect the console to a node server, but not sure whats wrong on registration
```
[webpush]$ connect -h pluto.fritz.box -p 8080
Connected to [pluto.fritz.box:8080][channelId=832513a6]
> Channel with id 832513a6, became inactive/disonnected.
[webpush]$ register --path /devices
Please use the connect command to connect to the server
[webpush]$
```

**Comment by danbev** [comment]
@matzew Not sure what the cause of this is. Is there any output in the node-webpush-server console? Tried the same with a similar host name but is still works.

**Comment by danbev** [comment]
@matzew Could you try adding a log statement in line ```419``` of ```node_modules/http2/lib/http.js```:
```javascript
console.log("servername = ", socket.servername);
```
And the restart the node-webpush-server and connect. Just to see if the SNI name looks correct.

**Comment by matzew** [comment]
Ok, I used the `webpush-console-7_0_67.zip` bundle (I am on Java7_65). and now it works.


I think this answers a question I had earlier, we are indeed 'required' to have several java 7 bundles, for different minor versions of java7 ?

**Comment by danbev** [comment]
>I think this answers a question I had earlier, we are indeed 'required' to have several java 7 bundles, for different minor versions of java7 ?

Yeah, different minor version require different version of NPN which is the reason for this.

**Comment by matzew** [comment]
> Yeah, different minor version require different version of NPN which is the reason for this.

Fun :smile: 

Would be good if the release blog post would address this with a sentence or two

**Comment by danbev** [comment]
Yeah, this is not nice at all but I'm afraid this is what it is. Let me add some more details regarding the minor versions to the readme for this to clarify it.

**Comment by matzew** [comment]
> Yeah, this is not nice at all but I'm afraid this is what it is. Let me add some more details regarding the minor versions to the readme for this to clarify it.

:+1: 

let's also have it in our blog post for aerogear.org

**Comment by danbev** [comment]
@matzew I've created https://github.com/aerogear/aerogear-webpush-server/pull/8 for this docs and I noticed that there where missing Java 1.7/NPN combinations.

**Comment by danbev** [comment]
@abstractj Sorry, I forgot you were on holiday. I'll get you next time :)
@matzew Thanks for reviewing!

**Pull request merged**
